"""G-code writer: turns toolpaths (lists of (x, y) points) into a .gcode
file, handling extrusion-length calculation, retraction, temperatures and
travel moves. Units: mm and degrees C throughout. Uses absolute X/Y/Z
positioning (G90) and relative extrusion (M83)."""
import math
from typing import List, Optional, Sequence, Tuple

from .config import PrintConfig

Point2 = Tuple[float, float]


class GCodeWriter:
    def __init__(self, config: PrintConfig):
        self.cfg = config
        self.lines: List[str] = []
        self.x: Optional[float] = None
        self.y: Optional[float] = None
        self.z: Optional[float] = None
        self.retracted = False
        self._layer_index = -1

    # -- low level -----------------------------------------------------
    def comment(self, text: str):
        self.lines.append(f"; {text}")

    def raw(self, line: str):
        self.lines.append(line)

    def _current_speed(self) -> float:
        return self.cfg.first_layer_speed if self._layer_index == 0 else self.cfg.print_speed

    # -- extrusion math --------------------------------------------------
    def _extrusion_for_length(self, length: float) -> float:
        """mm of filament needed to extrude a line of the given length,
        assuming a rectangular bead cross-section extrusion_width x layer_height."""
        cross_section_area = self.cfg.extrusion_width * self.cfg.layer_height
        volume = length * cross_section_area
        return volume / self.cfg.filament_area

    # -- high level moves ------------------------------------------------
    def travel_to(self, x: float, y: float):
        if self.x is not None:
            dist = math.hypot(x - self.x, y - self.y)
            if dist < 1e-6:
                return
        if not self.retracted and self.cfg.retraction_length > 0:
            self.retract()
        self.lines.append(
            f"G0 F{self.cfg.travel_speed * 60:.0f} X{x:.4f} Y{y:.4f}"
        )
        self.x, self.y = x, y

    def extrude_to(self, x: float, y: float, speed: Optional[float] = None):
        if self.x is None:
            self.x, self.y = x, y
            return
        dist = math.hypot(x - self.x, y - self.y)
        if dist < 1e-6:
            return
        if self.retracted:
            self.unretract()
        e = self._extrusion_for_length(dist)
        speed_mm_s = speed if speed is not None else self._current_speed()
        self.lines.append(
            f"G1 F{speed_mm_s * 60:.0f} X{x:.4f} Y{y:.4f} E{e:.5f}"
        )
        self.x, self.y = x, y

    def retract(self):
        if self.cfg.retraction_length <= 0 or self.retracted:
            return
        self.lines.append(
            f"G1 F{self.cfg.retraction_speed * 60:.0f} E{-self.cfg.retraction_length:.5f}"
        )
        self.retracted = True

    def unretract(self):
        if self.cfg.retraction_length <= 0 or not self.retracted:
            return
        self.lines.append(
            f"G1 F{self.cfg.retraction_speed * 60:.0f} E{self.cfg.retraction_length:.5f}"
        )
        self.retracted = False

    # -- toolpaths ---------------------------------------------------
    def print_polyline(self, points: Sequence[Point2], closed: bool = False):
        """Travel to the first point (retracting first), then extrude
        through the remaining points. If `closed`, also extrude back to
        the start point."""
        if not points:
            return
        pts = list(points)
        self.travel_to(*pts[0])
        for p in pts[1:]:
            self.extrude_to(*p)
        if closed:
            self.extrude_to(*pts[0])

    # -- layers / setup ------------------------------------------------
    def start_layer(self, layer_index: int, z: float):
        self._layer_index = layer_index
        self.comment(f"LAYER:{layer_index} Z:{z:.3f}")
        z_speed = self.cfg.travel_speed
        self.lines.append(f"G0 F{z_speed * 60:.0f} Z{z:.4f}")
        self.z = z

    def header(self):
        cfg = self.cfg
        self.comment("Generated by simple Python STL slicer")
        self.comment(
            f"layer_height={cfg.layer_height} extrusion_width={cfg.extrusion_width} "
            f"perimeters={cfg.num_perimeters} infill_density={cfg.infill_density}"
        )
        self.comment(
            f"nozzle_diameter={cfg.nozzle_diameter}mm filament_diameter={cfg.filament_diameter}mm"
        )
        self.raw("G21 ; units: millimeters")
        self.raw("G90 ; absolute X/Y/Z positioning")
        self.raw("M83 ; relative extrusion mode")
        self.raw(f"M140 S{cfg.bed_temp:.1f} ; set bed temp, don't wait")
        self.raw(f"M104 S{cfg.nozzle_temp:.1f} ; set nozzle temp, don't wait")
        self.raw(f"M190 S{cfg.bed_temp:.1f} ; wait for bed temp")
        self.raw(f"M109 S{cfg.nozzle_temp:.1f} ; wait for nozzle temp")
        self.raw("G28 ; home all axes")
        self.raw("G92 E0 ; reset extruder position")

    def footer(self):
        cfg = self.cfg
        self.comment("End of print")
        self.retract()
        self.raw(f"M104 S0 ; nozzle heater off")
        self.raw(f"M140 S0 ; bed heater off")
        self.raw("M84 ; disable motors")

    def to_string(self) -> str:
        return "\n".join(self.lines) + "\n"

    def write(self, path: str):
        with open(path, "w") as f:
            f.write(self.to_string())
